version: '3.4'

services:
  techchallengefiap.api:
    image: ${DOCKER_REGISTRY-}ifiap
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:80
    ports:
     - "8081:80"      
    depends_on:
     - sqldata


  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
     - SA_PASSWORD=#grupo@fiap!
     - ACCEPT_EULA=Y
    volumes:
     - c:\dados\volumes\mssql:/var/opt/mssql/data
    ports:
     - "1450:1433"