version: '3.4'

services:
  techchallengefiap.api:
    image: ${DOCKER_REGISTRY-}techchallengefiapapi
    build:
      context: .
      dockerfile: TechChallengeFIAP.Api/Dockerfile
    ports:
       - "8081:80"
    depends_on:
       - sqldata
  sqldata:
     image: mcr.microsoft.com/mssql/server:2019-latest
     environment:
       - SA_PASSWORD=ricardo#2024
       - ACCEPT_EULA=Y
     volumes:
       - C:\volumesqldatadocker:/var/opt/mssql/data
     ports:
       - "1450:1433"
