version: '3.4'

services:
  techchallengefiap.api:
    image: ${DOCKER_REGISTRY-}ifiap
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:80
    ports:
     - "8081:80"      
    depends_on:
     - sqldata


  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
     - SA_PASSWORD=Password@123
     - ACCEPT_EULA=Y
    volumes:
     - ./EstruturaDataBase.sql:/EstruturaDataBase.sql
    ports:
     - "1450:1433"
    command: /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30 & /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Password@123' -i /EstruturaDataBase.sql & wait"