apiVersion: v1
kind: Service
metadata:
  name: fiap-api-tech-service
spec:
  type: NodePort
  selector:
    app: fiap-api-tech
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 31000
