name: .NET Build and PR

on:
  push:
    branches:
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Restore dependencies
        run: dotnet restore ./TechChallengeFIAP.sln

      - name: Build the project
        run: dotnet build ./TechChallengeFIAP.sln --configuration Release --no-restore

  pr:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && contains(github.ref, 'feature/') || contains(github.ref, 'fix/')

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"title":"Automated Pull Request","body":"This PR was created automatically by GitHub Actions after a successful build.","head":"'"$BRANCH_NAME"'","base":"main"}' \
            https://api.github.com/repos/${{ github.repository }}/pulls
