name: .NET Build and PR

on:
  push:
    branches:
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Restore dependencies
        run: dotnet restore ./TechChallengeFIAP.sln

      - name: Build the project
        run: dotnet build ./TechChallengeFIAP.sln --configuration Release --no-restore
