name: .NET Build and PR

on:
  push:
    branches:
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Restore dependencies
        run: dotnet restore ./TechChallengeFIAP.sln

      - name: Build the project
        run: dotnet build ./TechChallengeFIAP.sln --configuration Release --no-restore

  pr:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && contains(github.ref, 'feature/') || contains(github.ref, 'fix/')

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Create pull request to main"
          title: "Automated PR to main"
          body: "This PR was created automatically by GitHub Actions."
          base: main
          branch: ${{ github.ref_name }}
